/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senai.tela;

import br.com.senai.dao.PlanoDao;
import br.com.senai.dao.PlanoDaoImpl;
import br.com.senai.entidade.Plano;
import br.com.senai.tela.PesquisarCliente;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilh
 */
public class Planos extends javax.swing.JFrame {

    
        private DefaultTableModel tabelaModelo;
        private PlanoDao planoDao = new PlanoDaoImpl();
        private List<Plano> planos;
        private Plano plano;
        
        
        
    public Planos() {
        initComponents();
        planoDao = new PlanoDaoImpl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varNomeAparelho = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePlano = new javax.swing.JTable();
        BTCadastra = new javax.swing.JButton();
        BTAlterar = new javax.swing.JButton();
        BTExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        varNomePlano = new javax.swing.JTextField();
        varValorPlano = new javax.swing.JTextField();
        varDescricaoPlano = new javax.swing.JTextField();
        BTPesquisar = new javax.swing.JButton();

        varNomeAparelho.setPreferredSize(new java.awt.Dimension(60, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Planos");

        jPanel1.setBackground(new java.awt.Color(64, 224, 208));

        tablePlano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome do plano", "Valor do Plano", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePlano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePlanoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePlano);

        BTCadastra.setText("Cadastrar");
        BTCadastra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTCadastra.setPreferredSize(new java.awt.Dimension(50, 23));
        BTCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCadastraActionPerformed(evt);
            }
        });

        BTAlterar.setText("Alterar");
        BTAlterar.setMaximumSize(new java.awt.Dimension(80, 22));
        BTAlterar.setMinimumSize(new java.awt.Dimension(80, 22));
        BTAlterar.setPreferredSize(new java.awt.Dimension(80, 22));
        BTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAlterarActionPerformed(evt);
            }
        });

        BTExcluir.setText("Excluir");
        BTExcluir.setMaximumSize(new java.awt.Dimension(80, 22));
        BTExcluir.setMinimumSize(new java.awt.Dimension(80, 22));
        BTExcluir.setPreferredSize(new java.awt.Dimension(80, 22));
        BTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Valor");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Descrição");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Planos");
        jLabel4.setMaximumSize(new java.awt.Dimension(315, 29));
        jLabel4.setMinimumSize(new java.awt.Dimension(315, 29));
        jLabel4.setPreferredSize(new java.awt.Dimension(315, 29));

        varNomePlano.setPreferredSize(new java.awt.Dimension(60, 23));

        varValorPlano.setPreferredSize(new java.awt.Dimension(60, 23));

        varDescricaoPlano.setPreferredSize(new java.awt.Dimension(60, 23));

        BTPesquisar.setText("Pesquisar");
        BTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(varDescricaoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(varValorPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(varNomePlano, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BTAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTPesquisar)
                        .addGap(34, 34, 34)
                        .addComponent(BTExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTPesquisar))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varNomePlano, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varValorPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varDescricaoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCadastraActionPerformed
        plano = new Plano();
        try {
            plano.setPlanos(varNomePlano.getText().trim());
            plano.setValorPlano(Integer.parseInt(varValorPlano.getText().trim()));
            plano.setDescricao(varDescricaoPlano.getText().trim());
                
        try {
            planoDao.salvar(plano);
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!!!");
            dispose(); 
        } catch (Exception ex) {
            Logger.getLogger(Plano.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception e) {
            System.out.println("Erro " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar Plano!");
        }
        
    }//GEN-LAST:event_BTCadastraActionPerformed

    private void BTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTPesquisarActionPerformed
        String nome = varNomePlano.getText().trim();
        if(nome.length() < 3){
            JOptionPane.showMessageDialog(null, "Digite pelo menos 3 letras!!");
        }else{
            try {
                planos = planoDao.pesquisarPorNome(nome);
                
                popularTabela();
            } catch (Exception ex) {
                Logger.getLogger(PesquisarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_BTPesquisarActionPerformed

    private void BTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAlterarActionPerformed
            int linhaSelecionada = tablePlano.getSelectedRow();
        try {
            Plano plano = planos.get(linhaSelecionada);
            plano.setPlanos(varNomePlano.getText().trim());
            plano.setDescricao(varDescricaoPlano.getText().trim());
            plano.setValorPlano(Integer.parseInt(varValorPlano.getText().trim()));
            planoDao.alterar(plano);
            JOptionPane.showMessageDialog(null, "SALVO COM SUCESSO!!!");  
            dispose();
            
        } catch (Exception e) {
            System.out.println("erro " + e);
            JOptionPane.showMessageDialog(null, "Erro ao alterar, selecione uma linha!");
        }

         
    }//GEN-LAST:event_BTAlterarActionPerformed

    private void BTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTExcluirActionPerformed
        int linhaSelecionada = tablePlano.getSelectedRow();
        try {
            Plano plano = planos.get(linhaSelecionada);
            planoDao.excluir(plano.getIdPlano());
            varNomePlano.setText(null);
            varValorPlano.setText(null);
            varDescricaoPlano.setText(null);
            JOptionPane.showMessageDialog(null, "Aparelhos excluido com sucesso!");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir, selecione uma linha");
        }
    }//GEN-LAST:event_BTExcluirActionPerformed

    private void tablePlanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePlanoMouseClicked
        int linhaSelecionada = tablePlano.getSelectedRow();
        Plano plano = planos.get(linhaSelecionada);
        varNomePlano.setText(plano.getPlanos());
        varValorPlano.setText(String.valueOf(plano.getValorPlano()));
        varDescricaoPlano.setText(plano.getDescricao());
        
    }//GEN-LAST:event_tablePlanoMouseClicked

        private void popularTabela(){
        tabelaModelo = (DefaultTableModel) tablePlano.getModel();
        tabelaModelo.setNumRows(0);
        for (Plano plano : planos) {
            tabelaModelo.addRow(new Object[]{plano.getPlanos(), plano.getValorPlano(),
                                 plano.getDescricao()});
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAlterar;
    private javax.swing.JButton BTCadastra;
    private javax.swing.JButton BTExcluir;
    private javax.swing.JButton BTPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePlano;
    private javax.swing.JTextField varDescricaoPlano;
    private javax.swing.JTextField varNomeAparelho;
    private javax.swing.JTextField varNomePlano;
    private javax.swing.JTextField varValorPlano;
    // End of variables declaration//GEN-END:variables
}
